### PR TITLE
attempting to address #72, XML to xml2

### PR DESCRIPTION
**Pull request by rsbivand**
This needs testing in production settings exercising more GRASS commands and on Windows and macOS:

```
devtools::install_github("rsbivand/rgrass", "xml2")
```

### CODE REVIEW

**Review by florisvdh — APPROVED** [review]
Thanks for addressing this!

I've run this version interactively against the `use.Rmd` vignette and some vector-based code. `execGRASS()` seems to work as expected. Deliberate errors (e.g. providing numeric instead of a character argument) are catched and reported.

`R CMD check --as-cran rgrass_0.4-1.tar.gz` runs OK (using GRASS 8.3.1).

I reviewed `DESCRIPTION` and your changes in `coerce.Rmd`, but did not review the code of `xml1.R`.

Done with R 4.3.2 on Linux Mint 21.2.

```
$ inxi -Sxxx
System:
  Host: _ Kernel: 5.15.0-89-generic x86_64 bits: 64 compiler: gcc
    v: 11.4.0 Desktop: Cinnamon 5.8.4 tk: GTK 3.24.33 wm: muffin vt: 7
    dm: LightDM 1.30.0 Distro: Linux Mint 21.2 Victoria
    base: Ubuntu 22.04 jammy
```

**Comment by rsbivand** [comment]
@florisvdh thanks! The code changes are only in `parseGRASS`, converting the XML returned by `--interface-description` to the (cached) internal representation used by `doGRASS` and `execGRASS`. The added test checks that the current version with `xml2` is the same as that created when using `XML`; the test is for `r.out.gdal`. Because `xml2` is vectorised but `XML` isn't, the conversion isn't completely obvious, but https://gist.github.com/nuest/3ed3b0057713eb4f4d75d11bb62f2d66 was a useful starting point.

**Review by veroandreo — APPROVED** [review]
I tested reading from and writing to GRASS db plus a series of basic commands like list, remove and info. All worked as expected :+1: 

Thanks @rsbivand !!!

**Comment by rsbivand** [comment]
@veroandreo Thanks! I'll submit to CRAN when submissions re-open in January.

**Pull request merged**
