### PR TITLE
Speed up and enhance reading from (and writing to) a GRASS GIS database

### LINKED ISSUE #75: Experimenting with reading straight from the GRASS database
With `read_RAST()` and `read_VECT()` GRASS is currently instructed to write a temp file using a `{v,r}.out.*` module, which may cause extra overhead and take disk space. It may be shortcut by using the [GDAL-GRASS GIS driver](https://github.com/OSGeo/gdal-grass) to read from the GRASS database. This is a standalone driver.

Current results from experimenting at the GRASS Community Meeting in Prague:

``` r
# If the drivers were compiled & installed from source 
# (https://github.com/OSGeo/gdal-grass), run:
# Sys.setenv(GDAL_DRIVER_PATH="/usr/lib/gdalplugins")
#
# But if installed from the ubuntugis-unstable PPA (`apt install libgdal-grass`),
# then it will just work out-of-the-box on Ubuntu
# See https://repology.org/project/gdal-grass/versions for other distros.

library(terra)
#> terra 1.7.29
library(rgrass)
#> Loading required package: XML
#> GRASS GIS interface loaded with GRASS version: (GRASS not running)

gdal(drivers = TRUE) |> 
  tibble::as_tibble() |> 
  dplyr::filter(stringr::str_detect(name, "GRASS|grass"))
#> # A tibble: 3 × 5
#>   name           type   can   vsi   long.name           
#>   <chr>          <chr>  <chr> <lgl> <chr>               
#> 1 GRASS          raster read  FALSE GRASS Rasters (7+)  
#> 2 GRASSASCIIGrid raster read  TRUE  GRASS ASCII Grid    
#> 3 OGR_GRASS      vector read  FALSE GRASS Vectors (5.7+)

initGRASS(
  home=tempdir(), 
  gisDbase="/home/floris/grassdata", 
  location="nc_basic_spm_grass7", 
  mapset="PERMANENT", 
  override=TRUE
  )
#> No gisBase set. Trying to detect from the GRASS_INSTALLATION environment variable.
#> No GRASS_INSTALLATION environment variable was found.
#> Trying to set gisBase by running command `grass --config path` (requires grass in the system PATH).
#> Taking gisBase value from `grass --config path` output: /usr/lib/grass82
#> gisdbase    /home/floris/grassdata 
#> location    nc_basic_spm_grass7 
#> mapset      PERMANENT 
#> rows        1350 
#> columns     1500 
#> north       228500 
#> south       215000 
#> west        630000 
#> east        645000 
#> nsres       10 
#> ewres       10 
#> projection:
#>  PROJCRS["NAD83(HARN) / North Carolina",
#>     BASEGEOGCRS["NAD83(HARN)",
#>         DATUM["NAD83 (High Accuracy Reference Network)",
#>             ELLIPSOID["GRS 1980",6378137,298.257222101,
#>                 LENGTHUNIT["metre",1]]],
#>         PRIMEM["Greenwich",0,
#>             ANGLEUNIT["degree",0.0174532925199433]],
#>         ID["EPSG",4152]],
#>     CONVERSION["SPCS83 North Carolina zone (meters)",
#>         METHOD["Lambert Conic Conformal (2SP)",
#>             ID["EPSG",9802]],
#>         PARAMETER["Latitude of false origin",33.75,
#>             ANGLEUNIT["degree",0.0174532925199433],
#>             ID["EPSG",8821]],
#>         PARAMETER["Longitude of false origin",-79,
#>             ANGLEUNIT["degree",0.0174532925199433],
#>             ID["EPSG",8822]],
#>         PARAMETER["Latitude of 1st standard parallel",36.1666666666667,
#>             ANGLEUNIT["degree",0.0174532925199433],
#>             ID["EPSG",8823]],
#>         PARAMETER["Latitude of 2nd standard parallel",34.3333333333333,
#>             ANGLEUNIT["degree",0.0174532925199433],
#>             ID["EPSG",8824]],
#>         PARAMETER["Easting at false origin",609601.22,
#>             LENGTHUNIT["metre",1],
#>             ID["EPSG",8826]],
#>         PARAMETER["Northing at false origin",0,
#>             LENGTHUNIT["metre",1],
#>             ID["EPSG",8827]]],
#>     CS[Cartesian,2],
#>         AXIS["easting (X)",east,
#>             ORDER[1],
#>             LENGTHUNIT["metre",1]],
#>         AXIS["northing (Y)",north,
#>             ORDER[2],
#>             LENGTHUNIT["metre",1]],
#>     USAGE[
#>         SCOPE["Engineering survey, topographic mapping."],
#>         AREA["United States (USA) - North Carolina - counties of Alamance; Alexander; Alleghany; Anson; Ashe; Avery; Beaufort; Bertie; Bladen; Brunswick; Buncombe; Burke; Cabarrus; Caldwell; Camden; Carteret; Caswell; Catawba; Chatham; Cherokee; Chowan; Clay; Cleveland; Columbus; Craven; Cumberland; Currituck; Dare; Davidson; Davie; Duplin; Durham; Edgecombe; Forsyth; Franklin; Gaston; Gates; Graham; Granville; Greene; Guilford; Halifax; Harnett; Haywood; Henderson; Hertford; Hoke; Hyde; Iredell; Jackson; Johnston; Jones; Lee; Lenoir; Lincoln; Macon; Madison; Martin; McDowell; Mecklenburg; Mitchell; Montgomery; Moore; Nash; New Hanover; Northampton; Onslow; Orange; Pamlico; Pasquotank; Pender; Perquimans; Person; Pitt; Polk; Randolph; Richmond; Robeson; Rockingham; Rowan; Rutherford; Sampson; Scotland; Stanly; Stokes; Surry; Swain; Transylvania; Tyrrell; Union; Vance; Wake; Warren; Washington; Watauga; Wayne; Wilkes; Wilson; Yadkin; Yancey."],
#>         BBOX[33.83,-84.33,36.59,-75.38]],
#>     ID["EPSG",3358]]

## RASTERS

# g.findfile hint comes from Vaclav Petras
filename_ras <- "elevation"
elevation_path_for_gdalgrass <- execGRASS(
  "g.findfile", 
  element = "cellhd", 
  file = filename_ras, 
  intern = TRUE,
  mapset = "PERMANENT"
  )[4]
elevation_path_for_gdalgrass <- regmatches(
  elevation_path_for_gdalgrass, 
  regexpr("(?<==['\"]).+(?=['\"]$)", elevation_path_for_gdalgrass, perl = TRUE)
  )
elevation_path_for_gdalgrass
#> [1] "/home/floris/grassdata/nc_basic_spm_grass7/PERMANENT/cellhd/elevation"

res <- rast(elevation_path_for_gdalgrass)
res
#> class       : SpatRaster 
#> dimensions  : 1350, 1500, 1  (nrow, ncol, nlyr)
#> resolution  : 10, 10  (x, y)
#> extent      : 630000, 645000, 215000, 228500  (xmin, xmax, ymin, ymax)
#> coord. ref. : +proj=lcc +lat_0=33.75 +lon_0=-79 +lat_1=36.1666666666667 +lat_2=34.3333333333333 +x_0=609601.22 +y_0=0 +ellps=GRS80 +units=m +no_defs 
#> source      : elevation 
#> color table : 1 
#> name        : elevation 
#> min value   :  55.57879 
#> max value   : 156.32986
inMemory(res)
#> [1] FALSE
# describe(elevation_path_for_gdalgrass)

stars::read_stars(elevation_path_for_gdalgrass)
#> stars object with 2 dimensions and 1 attribute
#> attribute(s), summary of first 1e+05 cells:
#>    elevation    
#>  121    : 2113  
#>  126    : 2086  
#>  133    : 1757  
#>  134    : 1645  
#>  135    : 1462  
#>  (Other): 7823  
#>  NA's   :83114  
#> dimension(s):
#>   from   to offset delta                       refsys x/y
#> x    1 1500 630000    10 +proj=lcc +lat_0=33.75 +l... [x]
#> y    1 1350 228500   -10 +proj=lcc +lat_0=33.75 +l... [y]
stars::read_stars(elevation_path_for_gdalgrass, proxy = TRUE)
#> stars_proxy object with 1 attribute in 1 file(s):
#> $elevation
#> [1] "[...]/elevation"
#> 
#> dimension(s):
#>   from   to offset delta                       refsys x/y
#> x    1 1500 630000    10 +proj=lcc +lat_0=33.75 +l... [x]
#> y    1 1350 228500   -10 +proj=lcc +lat_0=33.75 +l... [y]

## VECTORS

filename_vec <- "zipcodes"
zipcodes_path_for_gdalgrass <- execGRASS(
  "g.findfile", 
  element = "vector", 
  file = filename_vec, 
  intern = TRUE,
  mapset = "PERMANENT"
)[4]
zipcodes_path_for_gdalgrass <- regmatches(
  zipcodes_path_for_gdalgrass, 
  regexpr("(?<==['\"]).+(?=['\"]$)", zipcodes_path_for_gdalgrass, perl = TRUE)
) |> 
  paste0("/head")
zipcodes_path_for_gdalgrass
#> [1] "/home/floris/grassdata/nc_basic_spm_grass7/PERMANENT/vector/zipcodes/head"

vect(zipcodes_path_for_gdalgrass, layer = "zipcodes")
#> Warning in p@ptr$read(x, layer, query, extent, filter, proxy, what): GDAL Error
#> 1: Cannot reset cursor.
#> Warning in p@ptr$read(x, layer, query, extent, filter, proxy, what): GDAL Error
#> 1: Attributes not found.
#>  class       : SpatVector 
#>  geometry    : polygons 
#>  dimensions  : 48, 12  (geometries, attributes)
#>  extent      : 610047.9, 677060.7, 196327.5, 258102.6  (xmin, xmax, ymin, ymax)
#>  source      : head (zipcodes)
#>  coord. ref. : +proj=lcc +lat_0=33.75 +lon_0=-79 +lat_1=36.1666666666667 +lat_2=34.3333333333333 +x_0=609601.22 +y_0=0 +ellps=GRS80 +units=m +no_defs 
#>  names       :   cat OBJECTID WAKE_ZIPCO PERIMETER ZIPCODE_ ZIPCODE_ID
#>  type        : <int>    <int>      <num>     <num>    <num>      <num>
#>  values      :     1        1  2.625e+08 8.075e+04        2         27
#>                    2        2  3.163e+07 3.106e+04        7         25
#>                    3        3   5.44e+08 1.153e+05        8         20
#>      ZIPNAME    ZIPNUM           ZIPCODE        NAME SHAPE_Leng SHAPE_Area
#>        <chr>     <num>             <chr>       <chr>      <num>      <num>
#>    CREEDMOOR 2.752e+04   CREEDMOOR 27522   CREEDMOOR  8.078e+04  2.624e+08
#>  YOUNGSVILLE  2.76e+04 YOUNGSVILLE 27596 YOUNGSVILLE  3.106e+04  3.163e+07
#>      RALEIGH 2.762e+04     RALEIGH 27615     RALEIGH  1.153e+05   5.44e+08

sf::st_read(zipcodes_path_for_gdalgrass, layer = "zipcodes")
#> Reading layer `zipcodes' from data source 
#>   `/home/floris/grassdata/nc_basic_spm_grass7/PERMANENT/vector/zipcodes/head' 
#>   using driver `OGR_GRASS'
#> Simple feature collection with 48 features and 12 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: 610047.9 ymin: 196327.5 xmax: 677060.7 ymax: 258102.6
#> CRS:           NA

sf::sf_extSoftVersion()
#>           GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
#>       "3.11.1"        "3.6.2"        "9.1.1"         "true"         "true" 
#>           PROJ 
#>        "9.1.1"
terra::gdal()
#> [1] "3.6.2"
```

<sup>Created on 2023-06-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.0 (2023-04-21)
#>  os       Linux Mint 21.1
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language nl_BE:nl
#>  collate  nl_BE.UTF-8
#>  ctype    nl_BE.UTF-8
#>  tz       Europe/Brussels
#>  date     2023-06-05
#>  pandoc   2.19.2 @ /usr/lib/rstudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version   date (UTC) lib source
#>  abind         1.4-5     2016-07-21 [3] CRAN (R 4.2.0)
#>  class         7.3-22    2023-05-03 [3] RSPM (R 4.2.0)
#>  classInt      0.4-9     2023-02-28 [3] RSPM (R 4.2.0)
#>  cli           3.6.1     2023-03-23 [3] RSPM (R 4.2.0)
#>  codetools     0.2-19    2023-02-01 [3] RSPM (R 4.2.0)
#>  DBI           1.1.3     2022-06-18 [3] RSPM (R 4.2.0)
#>  digest        0.6.31    2022-12-11 [3] RSPM (R 4.2.0)
#>  dplyr         1.1.2     2023-04-20 [3] RSPM (R 4.2.0)
#>  e1071         1.7-13    2023-02-01 [3] RSPM (R 4.2.0)
#>  evaluate      0.21      2023-05-05 [3] RSPM (R 4.2.0)
#>  fansi         1.0.4     2023-01-22 [3] RSPM (R 4.2.0)
#>  fastmap       1.1.1     2023-02-24 [3] RSPM (R 4.2.0)
#>  fs            1.6.2     2023-04-25 [3] RSPM (R 4.2.0)
#>  generics      0.1.3     2022-07-05 [3] RSPM (R 4.2.0)
#>  glue          1.6.2     2022-02-24 [3] RSPM (R 4.2.0)
#>  htmltools     0.5.5     2023-03-23 [3] RSPM (R 4.2.0)
#>  KernSmooth    2.23-21   2023-05-03 [3] RSPM (R 4.2.0)
#>  knitr         1.43      2023-05-25 [3] RSPM (R 4.2.0)
#>  lifecycle     1.0.3     2022-10-07 [3] RSPM (R 4.2.0)
#>  lwgeom        0.2-13    2023-05-22 [3] RSPM (R 4.2.0)
#>  magrittr      2.0.3     2022-03-30 [3] RSPM (R 4.2.0)
#>  pillar        1.9.0     2023-03-22 [3] RSPM (R 4.2.0)
#>  pkgconfig     2.0.3     2019-09-22 [3] CRAN (R 4.0.1)
#>  proxy         0.4-27    2022-06-09 [3] RSPM (R 4.2.0)
#>  purrr         1.0.1     2023-01-10 [3] RSPM (R 4.2.0)
#>  R.cache       0.16.0    2022-07-21 [3] RSPM (R 4.2.0)
#>  R.methodsS3   1.8.2     2022-06-13 [3] RSPM (R 4.2.0)
#>  R.oo          1.25.0    2022-06-12 [3] RSPM (R 4.2.0)
#>  R.utils       2.12.2    2022-11-11 [3] RSPM (R 4.2.0)
#>  R6            2.5.1     2021-08-19 [3] RSPM (R 4.2.0)
#>  Rcpp          1.0.10    2023-01-22 [3] RSPM (R 4.2.0)
#>  reprex        2.0.2     2022-08-17 [3] RSPM (R 4.2.0)
#>  rgrass      * 0.3-9     2023-06-04 [1] local
#>  rlang         1.1.1     2023-04-28 [3] RSPM (R 4.2.0)
#>  rmarkdown     2.22      2023-06-01 [3] RSPM (R 4.2.0)
#>  rstudioapi    0.14      2022-08-22 [3] RSPM (R 4.2.0)
#>  sessioninfo   1.2.2     2021-12-06 [3] RSPM (R 4.2.0)
#>  sf            1.0-12    2023-03-19 [1] CRAN (R 4.3.0)
#>  stars         0.6-1     2023-04-06 [3] RSPM (R 4.2.0)
#>  stringi       1.7.12    2023-01-11 [3] RSPM (R 4.2.0)
#>  stringr       1.5.0     2022-12-02 [3] RSPM (R 4.2.0)
#>  styler        1.10.0    2023-05-24 [3] RSPM (R 4.2.0)
#>  terra       * 1.7-29    2023-04-22 [1] CRAN (R 4.2.3)
#>  tibble        3.2.1     2023-03-20 [3] RSPM (R 4.2.0)
#>  tidyselect    1.2.0     2022-10-10 [3] RSPM (R 4.2.0)
#>  units         0.8-2     2023-04-27 [3] RSPM (R 4.2.0)
#>  utf8          1.2.3     2023-01-31 [3] RSPM (R 4.2.0)
#>  vctrs         0.6.2     2023-04-19 [3] RSPM (R 4.2.0)
#>  withr         2.5.0     2022-03-03 [3] RSPM (R 4.2.0)
#>  xfun          0.39      2023-04-20 [3] RSPM (R 4.2.0)
#>  XML         * 3.99-0.14 2023-03-19 [3] RSPM (R 4.2.0)
#>  yaml          2.3.7     2023-01-23 [3] RSPM (R 4.2.0)
#> 
#>  [1] /home/floris/lib/R/library
#>  [2] /usr/local/lib/R/site-library
#>  [3] /usr/lib/R/site-library
#>  [4] /usr/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**sf** doesn't get a CRS though, and the others appear to get a PROJ string, maybe derived from the PROJ_INFO file (by the driver?) even though the EPSG code is set in the GRASS side.

@neteler @wenzeslaus

To be discussed.

### PR DESCRIPTION
**Pull request by florisvdh**
This PR attempts to address the following:

- **`read_RAST()`**, **`read_VECT()`**: implement the standalone [GDAL-GRASS drivers](https://github.com/OSGeo/gdal-grass) by default. This avoids exporting a GRASS GIS layer to a temporary file before reading into R. As a result one will get higher reading rates; this effect will increase with the size of the layer. Notes:
  - In `read_RAST()` this has only been implemented for the **terra** case, as it is the default.
  - Some issues still exist with the driver, such as a missing EPSG code. This is referred in the documentation. However the data are successfully returned.
  - The `v.out.ogr` and `r.out.gdal` pathways (writing a temporary file) remain in place when the necessary GDAL-GRASS driver is missing or if the `use_gdal_grass_driver` argument is set as `FALSE`.
  - in case the **terra** object already refers to a GRASS GIS database layer (i.e. has been created using the GDAL-GRASS driver), `write_RAST()` and `write_VECT()` will prevent calls to GRASS GIS to import such a source, as this would not succeed.
  - this closes #75.
- `read_VECT()`: provide support for the **`SpatVectorProxy`** class by adding a `proxy` argument (see [`terra::query()`](https://rspatial.github.io/terra/reference/query.html) to use `SpatVectorProxy` in R).
- arguments **`ignore.stderr`** and **`Sys_ignore.stdout`**: implement them in the default `execGRASS()` approach (uses `system2()`) – they were only implemented in the legacy approach – and make sure both arguments are exposed by `read_RAST()` and `read_VECT()`.
- **`write_VECT()`**: when the `SpatVector` object refers to a source file, a temporary GeoPackage is no longer written and the file is used directly by `v.in.ogr`. A similar shortcut was already implemented for `write_RAST()`.

Further testing, especially with Windows and macOS are most welcome!

A small benchmark is shown below.

<details><summary><strong>Code to create the benchmark</strong></summary>

``` r
library(dplyr, warn.conflicts = FALSE)
library(rgrass)
#> GRASS GIS interface loaded with GRASS version: (GRASS not running)
grass_conf <- initGRASS(
  gisBase = "/usr/lib/grass83",
  gisDbase = "/home/floris/grassdata",
  location = "nc_basic_spm_grass7",
  mapset = "PERMANENT",
  override = TRUE
)
vec_without_gdalgrass <- bench::mark(
  vec_without_gdalgrass = read_VECT(
    "streets",
    use_gdal_grass_driver = FALSE,
    ignore.stderr = TRUE
  ),
  iterations = 4
)
suppressWarnings({
  vec_with_gdalgrass <- bench::mark(
    vec_with_gdalgrass = read_VECT(
      "streets",
      use_gdal_grass_driver = TRUE
    ),
    iterations = 4
  )
})
rast_without_gdalgrass <- bench::mark(
  rast_without_gdalgrass = read_RAST(
    "elevation_shade",
    use_gdal_grass_driver = FALSE,
    ignore.stderr = TRUE
  ),
  iterations = 10
)
rast_with_gdalgrass <- bench::mark(
  rast_with_gdalgrass = read_RAST(
    "elevation_shade",
    use_gdal_grass_driver = TRUE
  ),
  iterations = 10
)

bind_rows(
  vec_without_gdalgrass,
  vec_with_gdalgrass,
  rast_without_gdalgrass,
  rast_with_gdalgrass
) |> 
  select(expression, min, median, iterations = n_itr) |> 
  knitr::kable()
```

</details>

| expression             |      min |   median | iterations |
|:-----------------------|---------:|---------:|-----------:|
| vec_without_gdalgrass  |   12.92s |   13.09s |          3 |
| vec_with_gdalgrass     |    4.13s |    4.18s |          4 |
| rast_without_gdalgrass | 476.39ms | 484.12ms |          9 |
| rast_with_gdalgrass    | 143.08ms | 146.35ms |          9 |

<sup>Created on 2024-06-16 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Some system specs:

```bash
$ ogrinfo --version
GDAL 3.8.4, released 2024/02/08
$ 
$ apt policy libgdal-grass
libgdal-grass:
  Installed: 1:1.0.2-7+jammy3
  Candidate: 1:1.0.2-7+jammy3
  Version table:
 *** 1:1.0.2-7+jammy3 500
        500 http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     3.4.1-3 500
        500 http://ftp.belnet.be/ubuntu jammy/universe amd64 Packages
$ 
$ inxi -Sxxx
System:
  Host: xxx Kernel: 5.15.0-112-generic x86_64 bits: 64 compiler: gcc
    v: 11.4.0 Desktop: Cinnamon 6.0.4 tk: GTK 3.24.33 wm: muffin vt: 7
    dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia
    base: Ubuntu 22.04 jammy
```

### CODE REVIEW

**Review by rsbivand — COMMENTED** [review]
I am deeply sceptical about this for the following reasons:

1. `terra` must be built against a GDAL installation that knows about the plugin for its GDAL version and platform. GDAL cannot be built in this way unless all the GRASS libraries it needs also being built. This may work for source installs on Linux/Unix, but cannot work for MXE/Rtools for Windows or for macOS/recipes, because using `terra` or `sf` or other R packages building against GDAL do not need that large extra burden. Using OSGEO4W will not work as MXE/Rtools build static for the chosen compilers using UCRT, but OSGEO4W has a mess of CRTs.
2. Previous experience even with the plugin was a nightmare, as the GDAL+plugin constantly got out of synch with other components. Since the plugin was dropped by GDAL, I haven't even tried to touch it. Any modifications would need very careful prior attention to all the build scenarios. Saying that the user has to sort these out is not going to work.
3. `terra` doesn't read raster data at all, but rather sets up an environment in C++ code pointing to the data source layer, unless forced to the `in.memory` setting. I really don't see any difference in the sense that when the `"spatRaster"` is `in.memory`, `terra` shadows the memory by a temporary file anyway, so instead of `r.out.gdal` then `rast` setting up pointers to the file created by `r.out.gdal`, `terra` would likely set up pointers to the single GRASS raster, but create a shadow file itself should the data be needed in the R workspace.
4. The `vect` case is slightly different, because `terra` always reads into a `"spatVector"` object, but I'm unsure whether there is always a shadow file.
5. If 1 and 2 can be shown to be feasible within reasonable developer time constraints. careful tests would be needed to show that the inclusion of the unproven (read only) driver is robust and scales.
6. Given more time, I could find even more reasons for not pursuing the plugin; data transfer speed really isn't important - the chosen raster format `"RRASTER"` is not compressed and is native for `terra`, and was upgraded by me to support `WKT2-2019`.

**Comment by hellik** [comment]
Point 1 by @rsbivand is an important one regarding winGRASS. Different GDAL versions built by different compilers may interfere. That's a packaging issue.

Though I find it an interesting approach worth to be followed.

The fallbacks are the methods currently used?

**Comment by florisvdh** [comment]
> The fallbacks are the methods currently used?

@hellik yes, if GDAL is not aware of the GDAL-GRASS driver (so indeed it needs to be set up correctly), the current implementation is used. In that case GRASS GIS is called with `r.out.gdal` or `v.out.ogr` to first write a temporary file either with the RRASTER (raster) or the GPKG (vector) GDAL driver, respectively.

For a binary driver installation that works out of the box Ubuntu-based systems, one can use the ubuntugis-unstable PPA, which is where the official GRASS GIS release lives, and install `libgdal-grass`. It is on par with its GRASS GIS and GDAL dependencies in the same repo. Still, to be user-friendly and work out of the box on all systems, it would indeed be great to have it natively included in GDAL.

These are the driver issues encountered a few days ago and posted at the driver repo, with help of @neteler: https://github.com/OSGeo/gdal-grass/issues/46, https://github.com/OSGeo/gdal-grass/issues/47, https://github.com/OSGeo/gdal-grass/issues/48.

**Comment by rsbivand** [comment]
So also this is bringing back code for example at: https://r-forge.r-project.org/scm/viewvc.php/pkg/rgrass7/R/bin_link.R?root=spgrass#l330, dropped on transfer to github. It was dropped because effectively nobody used the plugin, and because it was read-only. Please try some comparisons writing objects from R to GRASS using the plugin, as I think you suggest that it can write. I understand that this will only work for users with `terra` built from source against a GDAL built with the GRASS and OGR_GRASS drivers, so is effectively a reversion to how spgrass6 and rgrass7 used to work. It will not be available on platforms where `terra` is not built with driver-enabled GDAL.

**Comment by florisvdh** [comment]
> suggest that it can write

No, it's only relevant to `read_RAST()` and `read_VECT()`, since indeed it's a read-only driver. So in this PR the driver functionality is only added in `read_RAST()` and `read_VECT()`.

In relation to the driver, `write_*()` functions were only updated to refuse objects that already refer to a GRASS data source.

Apart from that, this PR also adds some `read_*()` and `write_*()` functionality that is agnostic to which approach is being used (see PR description).

> It will not be available on platforms where terra is not built with driver-enabled GDAL.

GDAL needs no specific configuration to use the driver; it uses its autoload mechanism to detect the driver and make it available. See https://github.com/OSGeo/gdal-grass/blob/main/README.md:

> _With this driver package you configure and install GDAL normally, then build and install GRASS normally and finally build and install this driver in [GDAL's "autoload" directory](https://gdal.org/user/configoptions.html#driver-management)._

On my system it was sufficient for {terra} to have been compiled against the GDAL version that was in place before the additional driver was installed. Also no additional `GDAL_DRIVER_PATH` environment variable (as documented at https://github.com/OSGeo/gdal-grass/blob/main/README.md) was needed for the driver to be detected, since the binary driver from the ubuntugis-unstable PPA is installed in an expected path:

```bash
$ locate gdalplugins | grep GRASS
/usr/lib/x86_64-linux-gnu/gdalplugins/gdal_GRASS.so
/usr/lib/x86_64-linux-gnu/gdalplugins/ogr_GRASS.so
```

**Comment by florisvdh** [comment]
> Running `rgrass` built from the `gdal_grass` branch fails `CMD check` with this log: [00check.log](https://github.com/user-attachments/files/15864349/00check.log)

Thanks. It's introduced by 682c7fc, 'needed' in order to not get the same error on my system, where there's no `rsb` mapset.

So since this error now pops up on your side I guess on your machine the `rsb` mapset will be the active mapset, so that `write_RAST()` writes the layers there, invoking the error.

The solution will be to be explicit about the mapset where new layers will be written. I suggest that we create a custom mapset explicitly in the examples, so that written layers end up there, not in `PERMANENT`. Do you agree @rsbivand?

**Comment by rsbivand** [comment]
Yes, @florisvdh creating a mapset to write into is a good idea in the examples; will you implement it?

**Review by veroandreo — COMMENTED** [review]
I tested the PR and works nicely, thanks @florisvdh! I just needed to create an .Renviron file with the `GDAL_DRIVER_PATH="/usr/lib/gdalplugins"` in `$HOME` and update `terra` to the latest version.

**Comment by florisvdh** [comment]
Thanks for testing @veroandreo !

**Comment by florisvdh** [comment]
@rsbivand Setting a mapset in the examples of this PR has now been taken care of (in `readRAST.Rd` and `readVECT.Rd`).

I discovered that the `vect2neigh()` example in `readVECT.Rd` still somehow modifies the `PERMANENT`  mapset by writing 3 extra layers into it (based on the `census` dataset). This happens even though the custom mapset is active. Since I won't soon have time to digg into this function (already returning from the GRASS GIS meeting), I have outcommented its example so that `PERMANENT` remains untouched.

**Comment by florisvdh** [comment]
While fiddling with mapsets and regions yesterday, it was discovered that the GDAL-GRASS driver does not respect a mapset's region. It just reads out a raster layer as it is stored in the GRASS GIS database. This is an important difference with `r.out.gdal`, which applies the mapset's region settings (extent & resolution).

As this causes inconsistency between the `r.out.gdal` approach (i.e. writing a temporary file for use by {terra}) and the GDAL-GRASS driver approach (direct reading), we cannot consider uptake of the GDAL-GRASS raster driver already.

Consequently I have reverted the use of the GDAL-GRASS raster driver in this PR (a828acf).

A corresponding driver feature request has been posted at https://github.com/OSGeo/gdal-grass/issues/49, so at least awaiting a solution for that one before reconsideration. For the driver it makes sense to take into account the region, since this GDAL driver is tailored for GRASS GIS.

Thanks @neteler and @veroandreo for the discussion about this yesterday.

Note that for vector datasets the region is not considered in GRASS GIS, so only the raster driver approach has been reverted.

**Comment by florisvdh** [comment]
> @florisvdh looks OK now, would you like to merge?

OK, let's do that. I'll add updates to `NEWS.md` and the pkgdown website before merging.

**Comment by florisvdh** [comment]
@rsbivand you can of course rephrase `NEWS.md` if needed. Thanks for reviewing this PR.

**Pull request merged**
