### PR TITLE
Fix pkgdown website (examples needed GRASS GIS context)

### PR DESCRIPTION
**Pull request by florisvdh**

### CODE REVIEW

**Review by rsbivand — APPROVED** [review]
Yes, the pkgdown site has typically been constructed inside GRASS in the `"nc_basic_spm_grass7"` location, and with `GRASS_INSTALLATION=/home/rsb/topics/grass/g832/grass83` set in the GRASS terminal before starting R.

**Comment by rsbivand** [comment]
The "Use of GRASS interface" vignette also needs the environment variable set to build the second part, "Starting GRASS inside R".

**Comment by florisvdh** [comment]
> The "Use of GRASS interface" vignette also needs the environment variable set to build the second part, "Starting GRASS inside R".

Yes; this vignette has not really changed (and no need to) since the code chunks are not evaluated.

I could build the pkgdown site update from R outside GRASS GIS after setting the environment with `initGRASS()` and then running `pkgdown::clean_site(); pkgdown::build_site()`.

**Comment by rsbivand** [comment]
@florisvdh please let me know when you feel I should submit to CRAN.

**Comment by rsbivand** [comment]
Submitted 2024-06-19 09:59 CEST.

**Comment by rsbivand** [comment]
Published 2024-06-19 12:58 CEST, there was a backlog of packages when I submitted, so 14 minutes from first appraisal to publication.

**Pull request merged**
